### ISSUE TITLE
Returning bug in browser

### ISSUE THREAD

**Issue by ITIVI** [rustcc/forustm#75]
I.Switching among pages,return to home page always;
II.Enter into a post,return to first page always;
III.Seems covering all blocks.

**Comment by DCjanus** [comment]
Fixed

**Comment by ITIVI** [comment]
It seems not.The problem still exists with all browsers,including firefox and chrome,even Edge and IE.

**Comment by DCjanus** [comment]
Just merged, no deploy yet.

**Comment by DCjanus** [comment]
Should be fixed, close this？

**Comment by miketang84** [comment]
close.
